defmodule LeaxerCoreWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :leaxer_core

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_leaxer_core_key",
    # Will be overridden by runtime config for security
    signing_salt: "LeaxerSession",
    same_site: "Lax"
  ]

  socket "/socket", LeaxerCoreWeb.UserSocket,
    websocket: [
      # Longer timeout for image generation (5 minutes)
      timeout: 300_000,
      # Check connection every 30 seconds
      check_origin: false,
      # Increase max frame size for file attachments (1MB)
      max_frame_size: 1_048_576
    ],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :leaxer_core,
    gzip: not code_reloading?,
    only: LeaxerCoreWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # Private Network Access - required for Tauri desktop app
  plug LeaxerCoreWeb.Plugs.PrivateNetworkAccess

  # CORS - must be before Router to handle preflight OPTIONS requests
  plug CORSPlug

  plug LeaxerCoreWeb.Router
end
