import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :leaxer_core, LeaxerCoreWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # This can be overridden by enabling "Allow LAN Access" in settings,
  # which is handled in runtime.exs when network_exposure_enabled is true.
  http: [
    ip: {127, 0, 0, 1},
    # Increase timeouts for long-running WebSocket connections during image generation
    # These are Bandit/Thousand Island transport options
    thousand_island_options: [
      # Time to wait for data on the socket (5 minutes for long generation)
      read_timeout: 300_000
    ]
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  # secret_key_base is now configured in config/runtime.exs via environment variables
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:leaxer_core, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:leaxer_core, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :leaxer_core, dev_routes: true

# Enable custom node hot-reload in development
# WARNING: Even with code purging, very frequent reloads could still grow the atom table.
# If you reload hundreds of unique module names, consider restarting the application.
config :leaxer_core, LeaxerCore.Nodes.Registry, hot_reload: true

# Use local model registry only (skip remote fetch) in development
config :leaxer_core, model_registry_local_only: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# CORS configuration is now centralized in config/runtime.exs
# In development, it uses sensible defaults based on PORT and UI_PORT env vars
# Override with CORS_ORIGINS="http://localhost:3000" if needed
