import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
# Desktop app doesn't need static asset caching (frontend is bundled separately)
config :leaxer_core, LeaxerCoreWeb.Endpoint,
  # cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: [
    "//localhost",
    "//127.0.0.1",
    "//tauri.localhost",
    "//*.tauri.localhost"
  ]

# Disable force_ssl for desktop app (runs locally)
# For web deployments, uncomment the force_ssl config below
# config :leaxer_core, LeaxerCoreWeb.Endpoint,
#   force_ssl: [rewrite_on: [:x_forwarded_proto]],
#   exclude: [
#     # paths: ["/health"],
#     hosts: ["localhost", "127.0.0.1"]
#   ]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
